{
  "uid" : "2b90617a989194a0",
  "name" : "test_run[run_case1]",
  "fullName" : "testcase.TestKeywords.TestKeyword#test_run[run_case1]",
  "historyId" : "8d5dfeb10adbb2d95195a9139c95dbbf",
  "time" : {
    "start" : 1589161429660,
    "stop" : 1589161429660,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'run' is not defined",
  "statusTrace" : "tp = <class 'NameError'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\six.py:692: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncmdopt = 'run'\n\n    @pytest.fixture(scope=\"session\")\n    def start_appium_desired(cmdopt):\n>       opt = eval(cmdopt)\nE       NameError: name 'run' is not defined\n\ntestcase\\conftest.py:21: NameError",
  "flaky" : true,
  "beforeStages" : [ {
    "name" : "start_appium_desired",
    "time" : {
      "start" : 1589161429652,
      "stop" : 1589161429652,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "NameError: name 'run' is not defined\n",
    "statusTrace" : "  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\cjj\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\cjj\\PycharmProjects\\Appium_AutoTest\\testcase\\conftest.py\", line 21, in start_appium_desired\n    opt = eval(cmdopt)\n  File \"<string>\", line 1, in <module>\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  }, {
    "name" : "cmdopt",
    "time" : {
      "start" : 1589161429652,
      "stop" : 1589161429652,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "TestKeywords"
  }, {
    "name" : "subSuite",
    "value" : "TestKeyword"
  }, {
    "name" : "host",
    "value" : "DESKTOP-0LL74L3"
  }, {
    "name" : "thread",
    "value" : "11040-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.TestKeywords"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "run_case",
    "value" : "{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=15797890689,password=1240055602CAI', '期望结果': '成功', '备注': '登录功能测试', '描述': '登录功能测试'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "e92f1e4304bd95e3",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1589161413384,
        "stop" : 1589161429026,
        "duration" : 15642
      }
    }, {
      "uid" : "bd2d9e5b12f2bf3b",
      "status" : "broken",
      "statusDetails" : "NameError: name 'run' is not defined",
      "time" : {
        "start" : 1589161356417,
        "stop" : 1589161356417,
        "duration" : 0
      }
    }, {
      "uid" : "7b5ce90f82fcae2d",
      "status" : "broken",
      "statusDetails" : "AttributeError: 'NoneType' object has no attribute 'launch_app'",
      "time" : {
        "start" : 1589161356361,
        "stop" : 1589161356361,
        "duration" : 0
      }
    }, {
      "uid" : "e9f919dd686f1c32",
      "status" : "broken",
      "statusDetails" : "NameError: name 'run' is not defined",
      "time" : {
        "start" : 1589161162829,
        "stop" : 1589161162829,
        "duration" : 0
      }
    }, {
      "uid" : "112bdb8bcb7dae56",
      "status" : "broken",
      "statusDetails" : "AttributeError: type object 'TestKeyword' has no attribute 'driver'",
      "time" : {
        "start" : 1589161131647,
        "stop" : 1589161162392,
        "duration" : 30745
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "2b90617a989194a0.json",
  "parameterValues" : [ "{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=15797890689,password=1240055602CAI', '期望结果': '成功', '备注': '登录功能测试', '描述': '登录功能测试'}" ]
}