{"name": "test_run[run_case1]", "status": "broken", "statusDetails": {"message": "NameError: name 'run' is not defined", "trace": "tp = <class 'NameError'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\six.py:692: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncmdopt = 'run'\n\n    @pytest.fixture(scope=\"session\")\n    def start_appium_desired(cmdopt):\n>       opt = eval(cmdopt)\nE       NameError: name 'run' is not defined\n\ntestcase\\conftest.py:21: NameError"}, "parameters": [{"name": "run_case", "value": "{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13718418220,password=112233', '期望结果': '成功', '备注': '登录功能测试', '描述': '登录功能测试'}"}], "start": 1589161162829, "stop": 1589161162829, "uuid": "a9f09fa8-7c5d-4519-8fcb-ef9499e7c582", "historyId": "8d5dfeb10adbb2d95195a9139c95dbbf", "fullName": "testcase.TestKeywords.TestKeyword#test_run[run_case1]", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "TestKeywords"}, {"name": "subSuite", "value": "TestKeyword"}, {"name": "host", "value": "DESKTOP-0LL74L3"}, {"name": "thread", "value": "14172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.TestKeywords"}]}